/* 独立验收页的测量附件。通过页面按钮启动，不打入候选游戏包。 */
const controls=document.createElement('div');controls.innerHTML='<button id="live30">四锅实测30秒</button><button id="curve30">限30帧跑400步</button><button id="curve60">限60帧跑400步</button><button id="liveResults">查看运行测量</button>';
document.querySelector('#game').before(controls);
async function gameRoot(){const w=document.querySelector('#game iframe')?.contentWindow;if(!w?.System)throw Error('先在下方打开游戏并点继续');const cc=await w.System.import('cc');const root=cc.director.getScene()?.getComponentsInChildren(cc.Component).find(c=>c.flow?.progress&&c.config);if(!root)throw Error('尚未进入营业');return {cc,root};}
const results=()=>{document.querySelector('#metrics').textContent=JSON.stringify(['qa.livePerf','qa.curve30','qa.curve60'].map(key=>({key,result:JSON.parse(localStorage.getItem(key)||'null')})),null,2);};
document.querySelector('#liveResults').onclick=results;
async function measure(fps,curve){try{const {cc,root}=await gameRoot();const flow=root.flow,sh=flow.shift;flow.paused=true;cc.game.frameRate=fps;
if(curve){const initial=fixtures[Number(document.querySelector('#case').value)].file.shift;Object.assign(sh.state,JSON.parse(JSON.stringify(initial)));}
const original=sh.step,steps=[],draw=[],states=[],start=performance.now();let last=start,drawSteps=0,maxDrawSteps=0,ended=false;
const before=JSON.parse(JSON.stringify(sh.state.pots));const startT=sh.state.t;
const end=()=>{if(ended)return;ended=true;sh.step=original;cc.director.off(cc.Director.EVENT_AFTER_DRAW,onDraw);if(curve)flow.paused=true;const sorted=draw.slice(1).sort((a,b)=>a-b);const result={candidate:'BT-20261003-RC07-67a5452fc67d',targetFPS:fps,kind:curve?'候选游戏实际限帧，重置相同测试样本后运行400次生产仿真':'候选游戏实际完成绘制间隔，四锅文火及蒸汽，包含测量开销',durationMs:performance.now()-start,draws:sorted.length,averageMs:sorted.reduce((a,b)=>a+b,0)/sorted.length,p50Ms:sorted[Math.floor(sorted.length*.5)],p95Ms:sorted[Math.floor(sorted.length*.95)],p99Ms:sorted[Math.floor(sorted.length*.99)],maxMs:sorted.at(-1),over50Ms:sorted.filter(x=>x>50).length,simulationSteps:steps.length,stepSeconds:[...new Set(steps)],maxStepsBetweenDraws:maxDrawSteps,startT,endT:sh.state.t,before,after:JSON.parse(JSON.stringify(sh.state.pots)),curve:states};localStorage.setItem(curve?'qa.curve'+fps:'qa.livePerf',JSON.stringify(result));results();};
function onDraw(){const now=performance.now();draw.push(now-last);last=now;maxDrawSteps=Math.max(maxDrawSteps,drawSteps);drawSteps=0;if(!curve&&now-start>=30000)end();}
sh.step=function(dt){if(ended)return original.call(this,dt);if(curve&&steps.length>=400){end();return;}original.call(this,dt);steps.push(dt);drawSteps++;if(curve&&steps.length%20===0)states.push(this.state.pots.map(p=>({doneness:Number(p.doneness.toFixed(9)),scorch:Number(p.scorch.toFixed(9)),stir:Number(p.stir.toFixed(9)),phase:p.phase})));if(curve&&steps.length===400)end();};
cc.director.on(cc.Director.EVENT_AFTER_DRAW,onDraw);flow.paused=false;document.querySelector('#metrics').textContent='正在测量：'+fps+'帧；'+(curve?'400步':'30秒')+'。测试样本，不是真人记录。';document.querySelector('#game').scrollIntoView();
}catch(e){document.querySelector('#metrics').textContent=String(e);}}
document.querySelector('#live30').onclick=()=>measure(60,false);document.querySelector('#curve30').onclick=()=>measure(30,true);document.querySelector('#curve60').onclick=()=>measure(60,true);
const stateButton=document.createElement('button');stateButton.textContent='查看即时游戏状态';controls.append(stateButton);stateButton.onclick=async()=>{try{const {root}=await gameRoot();const flow=root.flow;document.querySelector('#metrics').textContent=JSON.stringify({mode:flow.mode,paused:flow.paused,wallet:flow.progress.state.wallet,upgrades:flow.progress.state.upgrades,shift:flow.shift?.state??null},null,2);}catch(e){document.querySelector('#metrics').textContent=String(e);}};
